name: Build Check

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - 'docs/**'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/buildcheck.yml'

  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '.gitignore'
      - 'docs/**'
      - '*.md'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/buildcheck.yml'

jobs:
  single_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules : 'true'

    - name: Set up
      run: |
        vcpkg/bootstrap-vcpkg.sh
        vcpkg/vcpkg install

    - name: Configure
      run: ./config.sh

    - name: Make
      run: make

    # TODO run an actual set of checks
    - name: Run tests
      run: ./bin/champsim -w50000000 -i50000000 --json=single_core_result.json -- <(curl -s https://dpc3.compas.cs.stonybrook.edu/champsim-traces/speccpu/400.perlbench-41B.champsimtrace.xz | xz -dc)

    # We upload the generated files under github actions assets
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: champsim-singlecore-results
        path: single_core_result.json

  multi_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules : 'true'

    - name: Set up
      run: |
        vcpkg/bootstrap-vcpkg.sh
        vcpkg/vcpkg install

    - name: Configure
      run: './config.sh <(echo "{\"num_cores\": 2}")'

    - name: Make
      run: make

    # TODO run an actual set of checks
    - name: Run tests
      run: ./bin/champsim -w50000000 -i50000000 --json=multi_core_result.json -- <(curl -s https://dpc3.compas.cs.stonybrook.edu/champsim-traces/speccpu/400.perlbench-41B.champsimtrace.xz | xz -dc) <(curl -s https://dpc3.compas.cs.stonybrook.edu/champsim-traces/speccpu/401.bzip2-226B.champsimtrace.xz | xz -dc)

    # We upload the generated files under github actions assets
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: champsim-multicore-results
        path: multi_core_result.json
