name: lint

on:
  # Triggers the workflow on push events for develop
  push:
    branches:
      - develop

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: 'src inc prefetcher branch replacement btb tracer'
          style: file
          clangFormatVersion: 13.0.0
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Formatted with clang-format'
          default_author: github_actions
          add: 'src inc prefetcher branch replacement btb tracer'
